/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    solutions: Solution;
    services: Service;
    'case-studies': CaseStudy;
    insights: Insight;
    pages: Page;
    faqs: Faq;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    navigation: Navigation;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the meaningful content; use an empty visual only when the frontend deliberately marks it decorative.
   */
  alt: string;
  caption?: string | null;
  sourceCreator?: string | null;
  sourceUrl?: string | null;
  license: string;
  downloadedAt?: string | null;
  /**
   * Include disclosure limits, client approvals, or trademark concerns.
   */
  usageNotes?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: string;
  title: string;
  listingTitle: string;
  /**
   * Lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  kicker: string;
  summary: string;
  audience: string;
  image?: (string | null) | Media;
  /**
   * Used while approved repository assets are being migrated to R2.
   */
  fallbackImage?: string | null;
  imageAlt: string;
  imagePosition?: string | null;
  challengeTitle: string;
  challenge: string;
  painPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  capabilities?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  workflow?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  visual?: {
    eyebrow?: string | null;
    title?: string | null;
    primaryLabel?: string | null;
    primaryValue?: string | null;
    rows?:
      | {
          label: string;
          value: string;
          state: string;
          id?: string | null;
        }[]
      | null;
  };
  integrations?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  outcomes?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  relatedSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  listingTitle: string;
  /**
   * Lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  kicker: string;
  summary: string;
  audience: string;
  image?: (string | null) | Media;
  /**
   * Used while approved repository assets are being migrated to R2.
   */
  fallbackImage?: string | null;
  imageAlt: string;
  imagePosition?: string | null;
  challengeTitle: string;
  challenge: string;
  painPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  capabilities?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  workflow?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  visual?: {
    eyebrow?: string | null;
    title?: string | null;
    primaryLabel?: string | null;
    primaryValue?: string | null;
    rows?:
      | {
          label: string;
          value: string;
          state: string;
          id?: string | null;
        }[]
      | null;
  };
  integrations?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  outcomes?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  relatedSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string;
  title: string;
  listingTitle: string;
  /**
   * Lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  kicker: string;
  summary: string;
  image?: (string | null) | Media;
  /**
   * Used while approved repository assets are being migrated to R2.
   */
  fallbackImage?: string | null;
  imageAlt: string;
  imagePosition?: string | null;
  facts?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  challengeTitle?: string | null;
  challenge: string;
  roles?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  workflows?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  capabilities?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  technicalNotes?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  proof?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  testimonial?: (string | null) | Testimonial;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  quote: string;
  attribution: string;
  role?: string | null;
  company?: string | null;
  /**
   * Record who approved publication and where that approval is stored.
   */
  approvalReference: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: string;
  title: string;
  shortTitle: string;
  /**
   * Lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  excerpt: string;
  category: string;
  author: string;
  publishedAt: string;
  displayDate: string;
  readingTime: string;
  image?: (string | null) | Media;
  /**
   * Used while approved repository assets are being migrated to R2.
   */
  fallbackImage?: string | null;
  imageAlt: string;
  imagePosition?: string | null;
  introduction?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        id: string;
        title: string;
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        points?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  takeaways?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  relatedSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * Lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  layout?:
    | (
        | {
            kicker?: string | null;
            heading: string;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro';
          }
        | {
            heading: string;
            intro?: string | null;
            items?:
              | {
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading: string;
            body: string;
            image: string | Media;
            imageSide?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            heading: string;
            body?: string | null;
            label: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: string;
  topic?: ('General' | 'Solutions' | 'Services' | 'Process' | 'Support') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'solutions';
        value: string | Solution;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: string | CaseStudy;
      } | null)
    | ({
        relationTo: 'insights';
        value: string | Insight;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  sourceCreator?: T;
  sourceUrl?: T;
  license?: T;
  downloadedAt?: T;
  usageNotes?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  listingTitle?: T;
  slug?: T;
  kicker?: T;
  summary?: T;
  audience?: T;
  image?: T;
  fallbackImage?: T;
  imageAlt?: T;
  imagePosition?: T;
  challengeTitle?: T;
  challenge?: T;
  painPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  workflow?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  visual?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        primaryLabel?: T;
        primaryValue?: T;
        rows?:
          | T
          | {
              label?: T;
              value?: T;
              state?: T;
              id?: T;
            };
      };
  integrations?:
    | T
    | {
        text?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  relatedSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  listingTitle?: T;
  slug?: T;
  kicker?: T;
  summary?: T;
  audience?: T;
  image?: T;
  fallbackImage?: T;
  imageAlt?: T;
  imagePosition?: T;
  challengeTitle?: T;
  challenge?: T;
  painPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  workflow?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  visual?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        primaryLabel?: T;
        primaryValue?: T;
        rows?:
          | T
          | {
              label?: T;
              value?: T;
              state?: T;
              id?: T;
            };
      };
  integrations?:
    | T
    | {
        text?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  relatedSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  listingTitle?: T;
  slug?: T;
  kicker?: T;
  summary?: T;
  image?: T;
  fallbackImage?: T;
  imageAlt?: T;
  imagePosition?: T;
  facts?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  challengeTitle?: T;
  challenge?: T;
  roles?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  workflows?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  technicalNotes?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  proof?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  testimonial?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  shortTitle?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  displayDate?: T;
  readingTime?: T;
  image?: T;
  fallbackImage?: T;
  imageAlt?: T;
  imagePosition?: T;
  introduction?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        id?: T;
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  takeaways?:
    | T
    | {
        text?: T;
        id?: T;
      };
  relatedSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        intro?:
          | T
          | {
              kicker?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              imageSide?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  topic?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  role?: T;
  company?: T;
  approvalReference?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  hero: {
    kicker: string;
    title: string;
    description: string;
    primaryLabel: string;
    primaryHref: string;
    secondaryLabel: string;
    secondaryHref: string;
    scrollLabel: string;
  };
  sections: {
    audienceKicker: string;
    audienceTitle: string;
    solutionsKicker: string;
    solutionsTitle: string;
    workflowKicker: string;
    workflowTitle: string;
    carVuKicker: string;
    carVuTitle: string;
    carVuDescription: string;
    capabilitiesKicker: string;
    capabilitiesTitle: string;
    insightsKicker: string;
    insightsTitle: string;
  };
  finalCta: {
    kicker: string;
    title: string;
    description: string;
    label: string;
    href: string;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  primaryLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  serviceLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  proposalLabel: string;
  scheduleLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  kicker: string;
  title: string;
  description: string;
  ctaLabel: string;
  ctaHref: string;
  linkGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  publicEmail: string;
  phone?: string | null;
  whatsApp?: string | null;
  responsePromise?: string | null;
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    socialImage?: (string | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        title?: T;
        description?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
        scrollLabel?: T;
      };
  sections?:
    | T
    | {
        audienceKicker?: T;
        audienceTitle?: T;
        solutionsKicker?: T;
        solutionsTitle?: T;
        workflowKicker?: T;
        workflowTitle?: T;
        carVuKicker?: T;
        carVuTitle?: T;
        carVuDescription?: T;
        capabilitiesKicker?: T;
        capabilitiesTitle?: T;
        insightsKicker?: T;
        insightsTitle?: T;
      };
  finalCta?:
    | T
    | {
        kicker?: T;
        title?: T;
        description?: T;
        label?: T;
        href?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primaryLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  serviceLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  proposalLabel?: T;
  scheduleLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  kicker?: T;
  title?: T;
  description?: T;
  ctaLabel?: T;
  ctaHref?: T;
  linkGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  publicEmail?: T;
  phone?: T;
  whatsApp?: T;
  responsePromise?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
